from manim import *
from ..utils import *


class Part2_11_FourFundamentalSubspaces(LessonScene):
    def axes2d(self):
        ax = Axes(
            x_range=[-5, 5, 1], y_range=[-5, 5, 1],
            x_length=8.4, y_length=6.8,
            axis_config={"include_numbers": True, "stroke_width": 2},
        )
        ax.to_edge(LEFT, buff=0.35)
        return ax

    def eq(self, latex, scale=0.68, y=0):
        return MathTex(latex).scale(scale).to_edge(RIGHT, buff=0.25).shift(UP * y)

    def construct(self):
        self.title("Part II.11 — The Four Fundamental Subspaces", "How one matrix organizes input and output information")
        ax = self.axes2d()
        self.play(Create(ax))
        self.cc("A matrix does more than map inputs to outputs. It creates four closely related spaces that describe what information survives, what information disappears, and which directions are orthogonal to them.", 4)

        spaces = VGroup(
            MathTex(r"\operatorname{Col}(A)"),
            MathTex(r"\operatorname{Row}(A)"),
            MathTex(r"\operatorname{Null}(A)"),
            MathTex(r"\operatorname{Null}(A^T)"),
        ).scale(0.74).arrange(DOWN, aligned_edge=LEFT, buff=0.38).to_edge(RIGHT, buff=0.35).shift(UP * 0.8)
        self.play(LaggedStart(*[Write(x) for x in spaces], lag_ratio=0.35), run_time=2.4)
        self.cc("The column and row spaces describe directions generated by the matrix; the two null spaces describe directions annihilated by the matrix or its transpose.", 3.7)

        target = Arrow(ax.c2p(0, 0), ax.c2p(3, 1.5), buff=0, color=GREEN_C, stroke_width=7)
        self.play(GrowArrow(target))
        self.play(Write(self.eq(r"A\vec x\in\operatorname{Col}(A)", 0.85, -1.35)))
        self.cc("Every possible output Ax must live in the column space. That makes the column space the matrix's output subspace.", 3)

        self.play(FadeOut(target), FadeOut(spaces))
        row = Arrow(ax.c2p(0, 0), ax.c2p(2.5, 1), buff=0, color=VECTOR_A, stroke_width=7)
        null = Line(ax.c2p(-4, 2), ax.c2p(4, -2), color=HIGHLIGHT, stroke_width=7)
        left_null = Line(ax.c2p(-4, -2), ax.c2p(4, 2), color=YELLOW_C, stroke_width=6)
        self.play(GrowArrow(row), Create(null), Create(left_null))
        self.cc("Now separate the two kinds of zero-information directions: null vectors live in the input space, while left-null vectors live in the output space.", 3.4)
        self.play(Write(self.eq(r"A\vec x=\vec 0\quad\Rightarrow\quad\vec x\in\operatorname{Null}(A)", 0.66, 1.35)))
        self.cc("The null space contains input changes that the matrix completely loses.", 2.9)
        self.play(Write(self.eq(r"A^T\vec y=\vec 0\quad\Rightarrow\quad\vec y\in\operatorname{Null}(A^T)", 0.60, 0.2)))
        self.cc("The null space of the transpose contains output-space directions orthogonal to every column of A.", 3.1)
        self.play(Write(self.eq(r"\operatorname{Col}(A)\perp\operatorname{Null}(A^T)", 0.70, -0.85)))
        self.play(Write(self.eq(r"\operatorname{Row}(A)\perp\operatorname{Null}(A)", 0.70, -1.85)))
        self.cc("The second perpendicular pairing is just as important: the row space is orthogonal to the null space.", 3.2)
        self.play(Write(Text("Four spaces organize all input/output directions of a matrix.", font_size=26, color=YELLOW_B).to_edge(DOWN, buff=0.55)))
        self.wait(3)
